# Generated by Django 2.2.9 on 2019-12-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagecarouselimages_homeusepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeusepage',
            options={'verbose_name': 'Home Use Page', 'verbose_name_plural': 'Home Use Pages'},
        ),
    ]
