# Generated by Django 2.2.9 on 2020-01-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200105_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='related_page',
        ),
    ]
